2022-03-19 23:41:34,296 INFO    MainThread:6593 [wandb_setup.py:_flush():69] setting env: {}
2022-03-19 23:41:34,296 INFO    MainThread:6593 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-19 23:41:34,296 INFO    MainThread:6593 [wandb_init.py:_log_setup():342] Logging user logs to /home/oem/CMU/VLR/hw2/wandb/run-20220319_234134-1l28zwlf/logs/debug.log
2022-03-19 23:41:34,296 INFO    MainThread:6593 [wandb_init.py:_log_setup():343] Logging internal logs to /home/oem/CMU/VLR/hw2/wandb/run-20220319_234134-1l28zwlf/logs/debug-internal.log
2022-03-19 23:41:34,296 INFO    MainThread:6593 [wandb_init.py:init():375] calling init triggers
2022-03-19 23:41:34,296 INFO    MainThread:6593 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2022-03-19 23:41:34,296 INFO    MainThread:6593 [wandb_init.py:init():424] starting backend
2022-03-19 23:41:34,296 INFO    MainThread:6593 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-19 23:41:34,316 INFO    MainThread:6593 [backend.py:ensure_launched():135] starting backend process...
2022-03-19 23:41:34,332 INFO    MainThread:6593 [backend.py:ensure_launched():139] started backend process with pid: 6664
2022-03-19 23:41:34,333 INFO    MainThread:6593 [wandb_init.py:init():429] backend started and connected
2022-03-19 23:41:34,335 INFO    MainThread:6593 [wandb_init.py:init():477] updated telemetry
2022-03-19 23:41:34,335 INFO    MainThread:6593 [wandb_init.py:init():500] communicating current version
2022-03-19 23:41:35,194 INFO    MainThread:6593 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-19 23:41:35,194 INFO    MainThread:6593 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2022-03-19 23:41:35,406 INFO    MainThread:6593 [wandb_init.py:init():540] starting run threads in backend
2022-03-19 23:41:37,781 INFO    MainThread:6593 [wandb_run.py:_console_start():1601] atexit reg
2022-03-19 23:41:37,782 INFO    MainThread:6593 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.REDIRECT
2022-03-19 23:41:37,782 INFO    MainThread:6593 [wandb_run.py:_redirect():1480] Redirecting console.
2022-03-19 23:41:37,783 INFO    MainThread:6593 [wandb_run.py:_redirect():1536] Redirects installed.
2022-03-19 23:41:37,783 INFO    MainThread:6593 [wandb_init.py:init():565] run started, returning control to user process
2022-03-19 23:43:09,926 INFO    MainThread:6593 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 255
2022-03-19 23:43:09,926 INFO    MainThread:6593 [wandb_run.py:_restore():1543] restore
2022-03-19 23:43:12,403 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 828
  total_bytes: 828
}

2022-03-19 23:43:12,527 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 828
  total_bytes: 828
}

2022-03-19 23:43:12,711 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 828
  total_bytes: 828
}

2022-03-19 23:43:13,474 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 828
  total_bytes: 28651
}

2022-03-19 23:43:13,576 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 828
  total_bytes: 41238
}

2022-03-19 23:43:13,679 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 828
  total_bytes: 41238
}

2022-03-19 23:43:13,781 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28651
  total_bytes: 41238
}

2022-03-19 23:43:13,885 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 41238
  total_bytes: 41238
}

2022-03-19 23:43:13,988 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 41238
  total_bytes: 41238
}

2022-03-19 23:43:14,092 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 41238
  total_bytes: 41238
}

2022-03-19 23:43:14,202 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 41238
  total_bytes: 41238
}

2022-03-19 23:43:14,305 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 41238
  total_bytes: 41238
}

2022-03-19 23:43:14,484 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 41238
  total_bytes: 41238
}

2022-03-19 23:43:14,588 INFO    MainThread:6593 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 41238
  total_bytes: 41238
}

2022-03-19 23:43:15,704 INFO    MainThread:6593 [wandb_run.py:_show_files():1915] logging synced files
